### ISSUE TITLE
Add settings to suppress the alert dialog

### ISSUE THREAD

**Issue by petrdvorak** [tostringtheory/insomnia-plugin-accesstoken#2]
Currently, the plugin shows dialogs when calling request with an expired access token or when an access token is missing. This is useful sometimes, but annoying when testing APIs with intentionally expired or missing tokens.

It would be nice to add two checkboxes "Ignore missing tokens" and "Ignore expired tokens" to the settings that would suppress the dialogs.

**Comment by tostringtheory** [comment]
Hmm - seems simple enough and I get the reasoning, completely valid point.  I'll try and get to this by end of this weekend!

**Comment by petrdvorak** [comment]
Thank you! :) This would be great!

**Comment by tostringtheory** [comment]
@petrdvorak - sorry for the delay on this.  Other things had to take priority, but I finally had some catching up time this weekend.  I've just pushed an update to the plugin that allows for separate suppression of the expired/missing notification.  As well, another user wanted a use case where the prefix wasn't auto-prefixed, so the plugin now supports an `auth-prefix` tag, as well as another setting in the `access-token` tag to suppress the prefix.  By default though, it should continue operating how it does now.

**Comment by petrdvorak** [comment]
Thank you. :)
